FROM gcr.io/dnastack-container-store/liquibase-docker-image:1.0-2-gf48af98@sha256:ce4a85cc6cb6d3a6914cac6d1abb4eff2b718435c8565930c05fae564379be25
ADD db.changelog-master.yaml /db.changelog-master.yaml
