image:
  repository: gcr.io/dnastack-container-store # Docker repository to pull the image from

ingressRoute:
  enabled: true # Boolean indicating whether to generate Traefik ingress routes

app:
  name: data-connect-trino
  configVersion: config-version
  secretHash: secrets-hash
  memoryLimit: "1Gi"
  memoryRequest: "1Gi"
  oauth:
    clientSecretName: data-connect-trino-client-credentials # Secret name that contains the oauth client for all app interactions to external services e.g. data-connect-trino-client-credentials
  spring:
    profile: "wallet-auth,metrics-enabled,gcp" # Comma separated list of spring profiles to activate for this application
    datasource:
      hikari:
        maxPoolSize: "5" # Maximum number of connections in the database pool for this application

dataConnectTrino:
  appName: data-connect-trino # Host portion of the data-connect-trino URL to be used for authorization e.g. data-connect-trino

wallet:
  appName: wallet # Host portion of the wallet URL to be used for authorization e.g. wallet
  adminKubeKey: wallet-cloud-init-client-credentials # Name of k8s secret containing wallet clientId and clientSecret

auditLogService:
  appName: audit-log-service # Host portion of the audit-log-service URL e.g. audit-log-service
  enabled: false

indexingService:
  appName: indexing-service # Host portion of the indexing-service URL to be used for authorization e.g. indexing-service

collectionService:
  appName: collection-service # Host portion of the collection-service URL to be used for authorization e.g. collection-service

publisherData:
  appName: publisher-data # Host portion of the publisher-data URL to be used for authorization e.g. publisher-data

trino:
  appName: trino # Host portion of the trino URL to be used for authorization e.g. trino

database:
  jdbcUri: "jdbc:postgresql://postgres/dataconnecttrino" # JDBC Url for the application's main database e.g. "jdbc:postgresql://postgres/dataconnecttrino"
  postgresVersion: 14 # Version of the postgres server hosting the application's main database
  postgresInstance: "prod-postgres" # host name of the postgres server hosting the application's main database e.g. "prod-postgres"
  userSecretName: data-connect-trino-db-credentials # secret name that stores the credentials for the data-connect-trino database e.g. data-connect-trino-db-credentials

cloud:
  platform: "gcloud"
  project: kevin-test-07-25
  zone: us-central1-c
  region: us-central1
  clusterNamespace: prod
  spaceDnsName: kevin-test.helm-sandbox.dnastack.com

test:
  clientSecretName: data-connect-trino-e2e-test-client-credentials # E2E test data-connect-trino client secret name e.g. data-connect-trino-e2e-test-client-credentials
  inMemoryTestCatalog: "memory" # Name of the test catalog e.g. "memory"
  inMemoryTestSchema: "default"  # Name of the test schema e.g. "default"
  showSchemaForCatalogName: "publisher" # Name of a catalog that's expected to contain ar least one schema e.g. "publisher"
  showTableForCatalogSchemaName: "publisher.public" # Name of a catalog.schema that's expected to contain at least one table e.g. "publisher.data"
  keepalive:
    enabled: false" # boolean indicating whether e2e test pod should be kept alive to allow copy resources from it
    duration: 1800 # amount of time in seconds test pod will be kept alive