apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataconnecttrino
{{- if (coalesce .Values.image.secretName ((.Values.global).image).secretName) }}
imagePullSecrets:
  - name: "{{ coalesce .Values.image.secretName ((.Values.global).image).secretName }}"
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dataconnecttrino-{{ .Release.Namespace }}-edit-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: dataconnecttrino
    namespace: {{ .Release.Namespace }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-connect-trino
  labels:
    app.kubernetes.io/managed-by: Helm
    app: data-connect-trino
    configVersion: {{ .Values.app.configVersion }}
    secretsHash: {{ .Values.app.secretHash }}
    product: "data-connect"
    {{- range $key, $value := .Values.global.deploymentLabels }}
    {{ tpl ($key | toString) $ }}: {{ tpl ($value | toString) $ | quote }}
    {{- end }}
  annotations:
    meta.helm.sh/release-name: data-connect-trino
    meta.helm.sh/release-namespace: {{ coalesce .Values.cloud.clusterNamespace ((.Values.global).cloud).clusterNamespace }}
spec:
  selector:
    matchLabels:
      app: data-connect-trino
      configVersion: {{ .Values.app.configVersion }}
      secretsHash: {{ .Values.app.secretHash }}
  template:
    metadata:
      annotations:
        # forces rolling deployments on app upgrades
        rollme: {{ randAlphaNum 5 | quote }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
        {{- range $key, $value := .Values.global.templateAnnotations }}
        {{ tpl ($key | toString) $ }}: {{ tpl ($value | toString) $ | quote }}
        {{- end }}
      labels:
        app: data-connect-trino
        version: '{{- include  "dnastack.app.version" . }}'
        configVersion: {{ .Values.app.configVersion }}
        secretsHash: {{ .Values.app.secretHash }}
        product: "data-connect_spec"
        {{- range $key, $value := .Values.global.templateLabels }}
        {{ tpl ($key | toString) $ }}: {{ tpl ($value | toString) $ | quote }}
        {{- end }}
    spec:
      serviceAccountName: dataconnecttrino
      initContainers:
        - name: data-connect-trino-cloud-init
          image: '{{ coalesce .Values.image.repository ((.Values.global).image).repository }}/data-connect-trino-cloud-init-job:{{- include  "dnastack.cloudinit.version" . }}'
          command: [ "/cloud-init/run_cloud_init.sh" ]
          args: []
          env:
            - name: APP_NAME
              value: 'data-connect-trino'
            - name: DEPLOYMENT_ROOT_DIR
              value: '/cloud-init'
            - name: NAMESPACE
              value: '{{ coalesce .Values.cloud.clusterNamespace ((.Values.global).cloud).clusterNamespace }}'
            - name: CONFIG_VERSION
              value: '{{ .Values.app.configVersion }}'
            - name: SKIP_FILE_CONFIGS
              value: "true"
            - name: SKIP_REPO_CHECK
              value: "true"
            - name: SKIP_WALLET_INIT
              value: "true"
            - name: USE_LOCAL_HTTPIE
              value: "true"
            - name: USE_LOCAL_PSQL
              value: "true"
            - name: SHARED_POSTGRES_INSTANCE
              value: '{{ coalesce .Values.database.postgresInstance (((.Values.global).database).postgres).instance }}'
            - name: APP_POSTGRES_VERSION
              value: '{{ coalesce .Values.database.postgresVersion (((.Values.global).database).postgres).version }}'
            - name: USE_USER_TOKEN_FOR_ADMIN_ACTIONS
              value: "false"
            - name: TRINO_AUDIENCE
              value: '{{- include "dnastack.trino.resourceUrl" . }}'
            - name: APP_INDEXING_SERVICE_URL
              value: '{{- include "dnastack.indexingService.resourceUrl" . }}'
            - name: APP_COLLECTION_SERVICE_URL
              value: '{{- include "dnastack.collectionService.resourceUrl" . }}'
            - name: APP_DATA_CONNECT_TRINO_URL
              value: '{{- include "dnastack.dataConnectTrino.resourceUrl" . }}'
            - name: APP_PUBLISHER_DATA_URL
              value: '{{- include "dnastack.publisherData.resourceUrl" . }}'
            - name: WALLET_URL
              value: '{{- include "dnastack.wallet.internalUrl" . }}'
            - name: WALLET_RESOURCE
              value: '{{- include "dnastack.wallet.resourceUrl" . }}/'
            - name: WALLET_ADMIN_KUBEKEY
              value: "wallet-cloud-init-client-credentials"
            # Optional cloud-init environment variables
            {{- range .Values.cloudInitEnv }}
            - name: {{ .name }}
              {{- if .valueFrom  }}
              valueFrom:
                {{- if .valueFrom.fieldRef  }}
                fieldRef:
                  fieldPath: '{{ .valueFrom.fieldRef.fieldPath }}'
                {{- else}}
                secretKeyRef:
                  name: '{{ .valueFrom.secretKeyRef.name }}'
                  key: '{{ .valueFrom.secretKeyRef.key }}'
                {{- end}}
              {{- else }}
              value: '{{ .value }}'
              {{- end }}
            {{- end }}
          envFrom:
            - secretRef:
                name: publisher-cloud-init-secrets
                optional: true
            - configMapRef:
                name: cloud-init-env-vars
                optional: true
        - name: data-connect-trino-predeploy-job
          image: '{{ coalesce .Values.image.repository ((.Values.global).image).repository }}/data-connect-trino-predeploy-job:{{- include  "dnastack.app.version" . }}'
          command: ["/bin/sh", "-c"]
          args:
            - |
              liquibase \
               --driver=org.postgresql.Driver \
               --changeLogFile=/db.changelog-master.yaml \
               --url={{ include "dataConnectTrino.jdbcUri" . }} \
               --username=$(SPRING_DATASOURCE_USERNAME) \
               --password=$(SPRING_DATASOURCE_PASSWORD) \
               --logLevel debug \
               update
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-db-credentials'
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-db-credentials'
                  key: password
          envFrom:
            - secretRef:
                name: publisher-cloud-init-secrets
                optional: true
            - configMapRef:
                name: cloud-init-env-vars
                optional: true
      containers:
        - name: data-connect-trino
          image: '{{ coalesce .Values.image.repository ((.Values.global).image).repository }}/data-connect-trino:{{- include  "dnastack.app.version" . }}'
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: {{ .Values.app.memoryLimit }}
            requests:
              memory: {{ .Values.app.memoryLimit }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 18 # this will result in a 3 minutes timeout (periodSeconds * failureThreshold)
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
          env:
            - name: JAVA_OPTS
              value: "-XX:+PrintFlagsFinal -XX:+ExitOnOutOfMemoryError"
            - name: APP_URL
              value: '{{- include "dnastack.dataConnectTrino.externalUrl" . }}'
            - name: SPRING_PROFILES_ACTIVE
              value: "wallet-auth,metrics-enabled,cloud{{ if .Values.app.spring.additionalProfiles }},{{ .Values.app.spring.additionalProfiles }}{{ end }}"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: '{{ .Values.app.spring.datasource.hikari.maxPoolSize }}'
            - name: SPRING_LIQUIBASE_ENABLED
              value: "false"
            - name: TRINO_DATASOURCE_URL
              value: '{{- include "dnastack.trino.internalUrl" . }}'
            - name: TRINO_RESULTS_LIMIT_MAX
              value: "100"
            - name: TRINO_HIDDEN_CATALOGS
              value: "system,memory"
            - name: SERVER_PORT
              value: "8080"
            - name: APP_AUTH_TRINOOAUTHCLIENT_TOKENURI
              value: '{{- include "dnastack.wallet.internalUrl" . -}}/oauth/token'
            - name: APP_AUTH_TRINOOAUTHCLIENT_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-client-credentials'
                  key: clientId
            - name: APP_AUTH_TRINOOAUTHCLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-client-credentials'
                  key: clientSecret
            - name: APP_AUTH_TRINOOAUTHCLIENT_AUDIENCE
              value: '{{- include "dnastack.trino.resourceUrl" . }}'
            - name: APP_AUTH_TOKENISSUERS_0_ISSUERURI
              value: '{{- include "dnastack.wallet.externalUrl" . }}'
            - name: APP_AUTH_TOKENISSUERS_0_JWKSETURI
              value: '{{- include "dnastack.wallet.internalUrl" . -}}/oauth/jwks'
            - name: APP_AUTH_TOKENISSUERS_0_AUDIENCES_0
              value: '{{- include "dnastack.dataConnectTrino.externalUrl" . }}'
            - name: APP_SERVICE_INFO_ID
              value: "com.dnastack.data-connect"
            - name: APP_SERVICE_INFO_NAME
              value: 'data-connect-trino'
            - name: APP_SERVICE_INFO_VERSION
              value: '{{- include  "dnastack.app.version" . }}'
            - name: APP_SERVICE_INFO_DOCUMENTATION_URL
              value: "https://github.com/ga4gh-discovery/data-connect"
            - name: APP_SERVICE_INFO_CONTACT_URL
              value: "mailto:support@dnastack.com"
            - name: APP_SERVICE_INFO_DESCRIPTION
              value: "Supports data discovery by searching heterogeneous genomic and clinical data using a uniform query language."
            # Indexing service client
            - name: APP_INDEXING_SERVICE_ENABLED
              value: "true"
            - name: APP_INDEXING_SERVICE_BASE_URI
              value: '{{- include "dnastack.indexingService.internalUrl" . }}'
            - name: APP_INDEXING_SERVICE_OAUTH_CLIENT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-client-credentials'
                  key: clientId
            - name: APP_INDEXING_SERVICE_OAUTH_CLIENT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-client-credentials'
                  key: clientSecret
            - name: APP_INDEXING_SERVICE_OAUTH_CLIENT_RESOURCE
              value: '{{- include "dnastack.indexingService.resourceUrl" . }}/'
            - name: APP_INDEXING_SERVICE_OAUTH_CLIENT_TOKEN_URI
              value: '{{- include "dnastack.wallet.internalUrl" . -}}/oauth/token'
            - name: APP_INDEXING_SERVICE_OAUTH_CLIENT_TOKEN_ISSUERS_URIS
              value: '{{- include "dnastack.wallet.externalUrl" . }}'
            - name: APP_INDEXING_SERVICE_OAUTH_CLIENT_POLICY_EVALUATION_URI
              value: '{{- include "dnastack.wallet.internalUrl" . -}}/policies/evaluations'
            # Collection service client
            - name: APP_COLLECTION_SERVICE_ENABLED
              value: "true"
            - name: APP_COLLECTION_SERVICE_BASE_URI
              value: '{{- include "dnastack.collectionService.internalUrl" . }}'
            - name: APP_COLLECTION_SERVICE_OAUTH_CLIENT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-client-credentials'
                  key: clientId
            - name: APP_COLLECTION_SERVICE_OAUTH_CLIENT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-client-credentials'
                  key: clientSecret
            - name: APP_COLLECTION_SERVICE_OAUTH_CLIENT_RESOURCE
              value: '{{- include "dnastack.collectionService.resourceUrl" . }}/'
            - name: SPRING_DATASOURCE_URL
              value: {{ include "dataConnectTrino.jdbcUri" . }}
            - name: APP_COLLECTION_SERVICE_OAUTH_CLIENT_TOKEN_URI
              value: '{{- include "dnastack.wallet.internalUrl" . -}}/oauth/token'
            - name: APP_COLLECTION_SERVICE_OAUTH_CLIENT_TOKEN_ISSUERS_URIS
              value: '{{- include "dnastack.wallet.externalUrl" . }}'
            - name: APP_COLLECTION_SERVICE_OAUTH_CLIENT_POLICY_EVALUATION_URI
              value: '{{- include "dnastack.wallet.internalUrl" . -}}/policies/evaluations'
            - name: LOGGING_LEVEL_IO_MICROMETER
              value: INFO
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-db-credentials'
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 'data-connect-trino-db-credentials'
                  key: password
            # Auditing
            - name: AUDITING_ENABLED
              value: "true"
            # Datadog Config
            - name: DD_PROFILING_ENABLED
              value: "false"
            - name: DD_APPSEC_ENABLED
              value: "false"
            - name: DD_TRACE_PROPAGATION_STYLE
              value: "datadog,b3single,b3multi"
            - name: DD_TRACE_PARTIAL_FLUSH_MIN_SPANS
              value: "400"
            # Optional environment variables
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom  }}
              valueFrom:
                {{- if .valueFrom.fieldRef  }}
                fieldRef:
                  fieldPath: '{{ .valueFrom.fieldRef.fieldPath }}'
                {{- else}}
                secretKeyRef:
                  name: '{{ .valueFrom.secretKeyRef.name }}'
                  key: '{{ .valueFrom.secretKeyRef.key }}'
                {{- end}}
              {{- else }}
              value: '{{ .value }}'
              {{- end }}
            {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: data-connect-trino
  labels:
    app.kubernetes.io/managed-by: Helm
    name: data-connect-trino
  annotations:
    meta.helm.sh/release-name: data-connect-trino
    meta.helm.sh/release-namespace: {{ coalesce .Values.cloud.clusterNamespace ((.Values.global).cloud).clusterNamespace }}
spec:
  selector:
    app: data-connect-trino
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
